global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 5.0 #2
   publish_frequency: 5.0 #2
   width: 80.0
   height: 80.0
   resolution: 0.05
   static_map: true
   rolling_window: false
